package:
  name: gseapy
  version: "0.10.0"

source:
  url: https://files.pythonhosted.org/packages/ce/75/f0bdc8794ba191516b0022cfdcb462fac20609c97f0c0e7bdafd8f33d22c/gseapy-0.10.0.tar.gz
  sha256: 8062c0f4ec4f331377d90dcc90fbb98c74ee7bdcaff1fcc4df6fdc576b008a8d

build:
  noarch: python
  entry_points:
    - gseapy = gseapy.__main__:main
  number: 0

requirements:
  host:
    - python >3
    - setuptools
    - numpy >=1.13.0
    - scipy
    - pandas >=0.16
    - matplotlib-base >=1.4.3
    - beautifulsoup4 >=4.4.1
    - requests
    - lxml
    - html5lib
    - bioservices
    - joblib
  run:
    - python >3
    - numpy >=1.13.0
    - scipy
    - pandas >=0.16
    - matplotlib-base >=1.4.3
    - beautifulsoup4 >=4.4.1
    - requests
    - lxml
    - html5lib
    - bioservices
    - joblib

test:
  imports:
    - gseapy
  commands:
    - gseapy --help

about:
  home: https://github.com/zqfang/gseapy
  license: MIT License
  summary: 'Gene Set Enrichment Analysis in Python'
  license_family: MIT

extra:
  container:
    # matplotlib needs opengl support
    extended-base: true
