{% set name = "plantcv" %}
{% set version = "3.9.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "a00570af93835582135d869f34b87142415149922e05119bb1ed2ac7fe7f07a0"

build:
  noarch: python
  number: 0

requirements:
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - python
    - pip
  run:
    - python
    - python-dateutil
    - plotnine <=0.5.1
    - matplotlib-base >=1.5
    - numpy >=1.11
    - pandas
    - python-dateutil
    - scipy <1.3
    - scikit-image <0.15
    - opencv <4

test:
  commands:
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$BUILD_PREFIX/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64:$BUILD_PREFIX/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib"
    - python -c "import plantcv"
    - python -c "import plantcv.learn"
    - python -c "import plantcv.parallel"
    - python -c "import plantcv.plantcv"
    - python -c "import plantcv.plantcv.morphology"
    - python -c "import plantcv.plantcv.roi"
    - python -c "import plantcv.plantcv.threshold"
    - python -c "import plantcv.plantcv.transform"
    - python -c "import plantcv.plantcv.visualize"

about:
  home: https://plantcv.danforthcenter.org
  license: MIT License
  license_family: MIT
  license_file: 'LICENSE'
  summary: An image processing package for plant phenotyping.
  description: "PlantCV is a Python package for building modular image analysis workflows for plant phenotyping."
  doc_url: 'https://plantcv.readthedocs.io'
  dev_url: 'https://github.com/danforthcenter/plantcv'

extra:
  container:
    extended-base: true
  recipe-maintainers:
    - nfahlgren
    - maliagehan
    - HaleySchuhl
  identifiers:
    - doi:10.1016/j.molp.2015.06.005
    - doi:10.1109/WNYIPW.2016.7904790
    - doi:10.7717/peerj.4088
    - doi:10.7717/peerj.5727
